ncm-gadget/android-tools: add ncm to adb usb composite device
Change-Id: Ia643deae1ab04b99647fedf3ff91a08351aa3d66
Reviewed-on: https://gerrit-sha.synaptics.com/gerrit/294390
Reviewed-by: Steve Lau <Steve.Lau@synaptics.com>

diff --git a/dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-conf-configfs/android-gadget-setup b/dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-conf-configfs/android-gadget-setup
--- a/dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-conf-configfs/android-gadget-setup
+++ b/dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-conf-configfs/android-gadget-setup
@@ -1,53 +1,64 @@
 #!/bin/sh
 
-set -e
-
 manufacturer=Synaptics
 model="Android device"
-if [ -f /factory_setting/serialno ]; then
-  serial="$(cat /factory_setting/serialno)"
+COMMON_SCRIPT=/usr/bin/android-gadget-common.sh
+
+if [ ! -r "$COMMON_SCRIPT" ]; then
+  echo "Error: missing helper script $COMMON_SCRIPT" >&2
+  exit 1
 fi
 
-if [ "null$serial" == "null" ]; then
-  if grep chipid /proc/cmdline; then
-    serial=`awk -F'chipid=' '{print $2}'|awk '{print $1}'`
-  fi
-  if [ "null$serial" == "null" ]; then
-    serial=`cat /etc/hostname`
-  fi
-  if [ "null$serial" == "null" ]; then
-    serial="SLx6x0"
-  fi
-fi
+. "$COMMON_SCRIPT"
+serial="$(detect_serial)"
 
-if [ -r /etc/android-gadget-setup.machine ] ; then
-	. /etc/android-gadget-setup.machine
+if [ -r /etc/android-gadget-setup.machine ]; then
+  . /etc/android-gadget-setup.machine
 fi
 
 [ -d /sys/kernel/config/usb_gadget ] || modprobe libcomposite
 
-cd /sys/kernel/config/usb_gadget
+create_android_gadget_defaults() {
+  mkdir -p strings/0x409
+  mkdir -p configs/c.1
+  mkdir -p configs/c.1/strings/0x409
 
-[ -d adb ] && /usr/bin/android-gadget-cleanup || true
+  echo -n 0x1d6b > idVendor
+  echo -n 0x0104 > idProduct
+  echo "$serial" > strings/0x409/serialnumber
+  echo "$manufacturer" > strings/0x409/manufacturer
+  echo "$model" > strings/0x409/product
+  echo "Conf 1" > configs/c.1/strings/0x409/configuration
+}
 
-mkdir adb
-cd adb
+cd /sys/kernel/config/usb_gadget || exit 1
+find_or_create_gadget g1 create_android_gadget_defaults
 
-mkdir configs/c.1
-mkdir functions/ffs.usb0
-mkdir strings/0x409
-mkdir configs/c.1/strings/0x409
-echo -n 0x18d1 > idVendor
-echo -n 0xd002 > idProduct
-echo "$serial" > strings/0x409/serialnumber
-echo "$manufacturer" > strings/0x409/manufacturer
-echo "$model" > strings/0x409/product
-echo "Conf 1" > configs/c.1/strings/0x409/configuration
-ln -s functions/ffs.usb0 configs/c.1
+# Temporarily disable gadget before adding/removing configfs links.
+if [ -r UDC ] && [ -s UDC ]; then
+  udc_name=$(cat UDC 2>/dev/null)
+  if [ -n "$udc_name" ] && [ "$udc_name" != "off" ]; then
+    echo "Disabling gadget temporarily to add ADB function" >&2
+    echo "" > UDC
+    sleep 1
+  fi
+fi
+
+if [ ! -d functions/ffs.usb0 ]; then
+  mkdir -p functions/ffs.usb0
+fi
+
+if [ ! -L configs/c.1/ffs.usb0 ]; then
+  ln -s functions/ffs.usb0 configs/c.1/ffs.usb0
+fi
 
 if [ -f /sys/bus/usb/devices/usb3/power/autosuspend ]; then
-  echo 10 > /sys/bus/usb/devices/usb3/power/autosuspend
+  echo 10 > /sys/bus/usb/devices/usb3/power/autosuspend 2>/dev/null || true
 fi
 
 mkdir -p /dev/usb-ffs/adb
-mount -t functionfs usb0 /dev/usb-ffs/adb
+mount -t functionfs usb0 /dev/usb-ffs/adb 2>/dev/null || true
+
+enable_gadget_udc
+
+exit 0
diff --git a/dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-conf-configfs/android-gadget-start b/dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-conf-configfs/android-gadget-start
--- a/dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-conf-configfs/android-gadget-start
+++ b/dynamic-layers/openembedded-layer/recipes-devtools/android-tools/android-tools-conf-configfs/android-gadget-start
@@ -1,23 +1,17 @@
 #!/bin/sh
 
-#Not report error in case write UDCfile failed sometime, can retry again
-#set -e
+# Android gadget start - re-enable gadget on UDC (called via udev)
+# Waits for FunctionFS (ep2) to be available before enabling
 
-usb_controller=`ls /sys/class/udc`
-UDCfile=/sys/kernel/config/usb_gadget/adb/UDC
-ep2file=/dev/usb-ffs/adb/ep2
+COMMON_SCRIPT=/usr/bin/android-gadget-common.sh
 
-i=10
-while [ $i -gt 0 ]
-do
-    usb_controllerInUDC=`cat ${UDCfile}`
-    if [ -f ${ep2file} ] && [ "${usb_controllerInUDC}" != "${usb_controller}" ]; then
-        echo ${usb_controller} > ${UDCfile}
-	if [ $? != 0 ]; then
-	    echo "Write usb_controller ${usb_controller} to ${UDCfile} failed!"
-	fi
-	break
-    fi
-    i=$((i-1))
-    sleep 3
-done
+if [ ! -r "$COMMON_SCRIPT" ]; then
+  echo "Error: missing helper script $COMMON_SCRIPT" >&2
+  exit 1
+fi
+
+. "$COMMON_SCRIPT"
+enable_gadget_udc_with_retry 10 3 /dev/usb-ffs/adb/ep2
+
+exit 0
+
